RoiPoolingConv <- R6::R6Class(
  "RoiPoolingConv",
  inherit = keras::KerasLayer,

  public = list(

    pool_size = NULL,
    num_rois = NULL,
    n_channels = NULL,

    initialize = function(pool_size, num_rois) {
      self$pool_size <- as.integer(pool_size)
      self$num_rois <- as.integer(num_rois)
    },

    build = function(input_shape) {
      self$n_channels <- input_shape[[1]]$as_list()[[4]]
    },

    compute_output_shape = function(input_shape) {
      c(self$num_rois, self$pool_size, self$pool_size, self$n_channels)
    },

    call = function(x, mask = NULL) {

      img <- x[[1]]
      rois <- x[[2]]

      output <- lapply(seq_len(self$num_rois), function(i) {

        x <- keras::k_cast(rois[1, i, 1], dtype = "int32")
        y <- keras::k_cast(rois[1, i, 2], dtype = "int32")
        w <- keras::k_cast(rois[1, i, 3], dtype = "int32")
        h <- keras::k_cast(rois[1, i, 4], dtype = "int32")

        row_length = w / self$pool_size
        col_length = h / self$pool_size

        withr::with_options(c(tensorflow.extract.warn_tensors_passed_asis = FALSE), {
          tensorflow::tf$image$resize(
            img[,y:(y+h), x:(x+w),],
            size = rep(self$pool_size, 2)
          )
        })
      })

      output %>%
        keras::k_concatenate(axis = 0) %>%
        keras::k_reshape(
          shape = shape(
            1, self$num_rois, self$pool_size, self$pool_size, self$n_channels
          )
        )
    }

  )

)

#' RoI Pooling Layer
#'
#' @param object Model or layer object
#' @param pool_size Size of pooling region to use. pool_size = 7 will result in
#'  a 7x7 region.
#' @param num_rois number of regions of interest to be used
#' @param name An optional name string for the layer. Should be unique in a model
#'  (do not reuse the same name twice). It will be autogenerated if it isn't
#'  provided.
#' @param trainable Whether the layer weights will be updated during training.
#'
#' @export
layer_roi_pooling_conv <- function(object, pool_size, num_rois, name = NULL, trainable = TRUE) {
  create_layer(RoiPoolingConv, object, list(
    pool_size = pool_size,
    num_rois = num_rois,
    name = name,
    trainable = trainable
  ))
}
